### ISSUE TITLE
rice starting up with the debug prompt

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#11]
as of rice version 0.0.13 it seems to be starting up with the debug prompt rather than the regular one. I can fix it by explicitly setting a prompt.

```shell
> rice
R version 3.4.1 Patched (2017-08-06 r73048) -- Single Candle
Platform: x86_64-apple-darwin15.6.0

debug%>

debug%> options(prompt = "> ")

> 
```

This is likely a regression in relation to https://github.com/randy3k/rice/issues/9

**Comment by randy3k** [comment]
Sorry for the error, fixed.

**Comment by jimhester** [comment]
Thanks!

This is almost correct now, except that it overwrites an existing `options(prompt)` value set in `.RProfile`. e.g. I set `options(prompt = "> ")` in .Rprofile, but the value is changed to "r$> " when I start rice. If I change the option interactively it correctly updates however.

**Comment by randy3k** [comment]
When rice starts, it detects if `options("prompt")` is `"> "` and change it to `"r$> "`.  Therefore, the value is changed to `r$> `.

A solution to it is to add an option `"rice.prompt"` which will over write rice default prompt `r$> `

**Comment by jimhester** [comment]
Ah that makes sense, If you would like to add an option that is fine, or I can just change my prompt from the default.
