### ISSUE TITLE
Indentation when copying mulit-line functions

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#12]
If you copy a multi-line function into a rice terminal rice adds extra indentation.

Given a function
```r
foo <- function(x) {
  x <- x + 1
  x <- x + 2
  x <- x + 3
}
```

If I open rice and copy the full lines into rice I get the following
```shell
rice
R version 3.4.1 Patched (2017-08-06 r73048) -- Single Candle
Platform: x86_64-apple-darwin15.6.0

r$> foo <- function(x) {
      x <- x + 1
        x <- x + 2
          x <- x + 3
          }
r$>
```

I guess due to the prompt toolkit trying to be helpful for python's significant whitespace. But since R doesn't have indentation significant whitespace it would be nicer if this reproduced the original formatting.

You get better the expected behavior if you copy the full function as a block rather than line-by-line

**Comment by randy3k** [comment]
Did you copy the lines one by one? Are you using something like Nvim-R to send those lines?

**Comment by randy3k** [comment]
Actually, it is myself added this feature https://github.com/randy3k/rice/blob/1e421053990446bbad4a6a415458fb682f61ca96/rice/keybinding.py#L66-L66

**Comment by jimhester** [comment]
Yes I am using Nvim-R to send the lines usually (where I first noticed this issue), but it also happens if you just copy the lines one by one.

**Comment by randy3k** [comment]
@jalvessq and I had some discussions here https://github.com/jalvesaq/Nvim-R/issues/227

He implemented an option 
```
let R_source_args = "bracketed paste"
```

This option doesn't alter the behavior of `\l` but that of `\ss` and `\ff`. This may not be exactly what you want (I didn't). You can check if you like it or not.

A more permanent solution is to write a function `<Plug>RDSendSelectionBracketed` and bind `\l` to it in the visual mode.

**Comment by randy3k** [comment]
An temporary solution for rice is to add an option in rice to control the auto indentation.

**Comment by jimhester** [comment]
I have a key bound to `<Plug>RDSendLine` in normal mode and `<Plug>REDSendSelection` in visual mode. The latter works fine, the former exhibits the behavior I described (as does copying the lines manually).

👍 on an option to control the indentation

**Comment by randy3k** [comment]
close by v0.0.14

**Comment by jimhester** [comment]
Setting `options(rice.auto_indentation = FALSE)` seems to have no effect as far as I can tell, the behavior remains the same as before.

With rice versions 0.0.14 and 0.0.21.

**Comment by randy3k** [comment]
It seems that there is a bug in parsing rice settings. Will fix soon

**Comment by randy3k** [comment]
It is strange, 0.0.21 works for me. Could you check `options("rice.auto_indentation")` in rice console?

**Comment by randy3k** [comment]
By the way, you need to set it up in `.Rprofile` as it won't be loaded dynamically.

**Comment by jimhester** [comment]
See https://asciinema.org/a/7GbLlcLxhosnci1UjoKnmzfJ8 for what it is doing on my machine, this is just copy pasting into a rice terminal, without Nvim-R at all.

An additional issue that has appeared is rice seems to be stripping the trailing newline when pasting and I now have to explicitly hit enter to start a new line. Previous behavior retained the pasted newline, which is what I would prefer.

**Comment by randy3k** [comment]
let's keep this open.

**Comment by randy3k** [comment]
I understand what is going on now, `rice.auto_indentation` now only disable the indentation after the braces. What you are experiencing is an automatic indentation based on the indentation of the previous line, and it was designed by prompt_toolkit. I guess I have to also turn that off.

**Comment by randy3k** [comment]
I can also reproduce stripping newline issue.

**Comment by randy3k** [comment]
The stripping newline issue has fixed 8349baf

**Comment by randy3k** [comment]
The indentation issue is fixed b24a0e68da1ca1a8c334aea0e1562383316fb79c

**Comment by randy3k** [comment]
v0.0.23 should have addressed all these.

Btw, thank you for the feedbacks. They are extremely helpful.

**Comment by jimhester** [comment]
Thanks for your persistence, can confirm it is now fixed!

**Comment by randy3k** [comment]
Just want to let you know that Nvim-R now supports bracketed paste mode https://github.com/jalvesaq/Nvim-R/pull/258 so you just need to put
```
let g:R_bracketed_paste = 1
```

and Nvim-R will send the R code with bracketed paste without worrying the auto indentation. In other words, with this settings, a user can enjoy the auto indentation in the console, while the code sends through Nvim-R will not trigger auto indentation (as well as auto matching quotes/ parens).
