### ISSUE TITLE
python callback attempting to attach package

### ISSUE THREAD

**Issue by pjc42** [randy3k/rice#16]
**issue with attaching packages**

`
r$> library(tidyverse)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "b:\python\anaconda3_4.3.1\envs\rice\lib\site-packages\rice\callbacks.py", line 31, in write_console_ex
    output = buf.decode(ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 44: invalid start byte

r$> library(dplyr)
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "b:\python\anaconda3_4.3.1\envs\rice\lib\site-packages\rice\callbacks.py", line 31, in write_console_ex
    output = buf.decode(ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 44: invalid start byte

`

**here is the pip info from the install this morning:**

`
> pip install -U rice
Collecting rice
  Downloading rice-0.0.18.tar.gz (244kB)
    100% |████████████████████████████████| 245kB 1.2MB/s
Requirement already up-to-date: pygments in b:\python\anaconda3_4.3.1\envs\rice\lib\site-packages (from rice)
Collecting six (from rice)
  Downloading six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: wcwidth in b:\python\anaconda3_4.3.1\envs\rice\lib\site-packages (from rice)
Building wheels for collected packages: rice
  Running setup.py bdist_wheel for rice ... done
  Stored in directory: C:\Users\pjc\AppData\Local\pip\Cache\wheels\b0\1d\ce\0494449c54c5f7fa0bf7fc86cd2c4c5d1372ff9c85201e51e8
Successfully built rice
Installing collected packages: six, rice
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: rice 0.0.9
    Uninstalling rice-0.0.9:
      Successfully uninstalled rice-0.0.9
Successfully installed rice-0.0.18 six-1.11.0
`

**Comment by randy3k** [comment]
Windows encoding and unicode handling have been bugging me for a while. Could you report this from the regular R console?

```
Sys.getlocale()
l10n_info()
```

**Comment by randy3k** [comment]
Oh. I know what is happening, it is due to a recent refactoring.

**Comment by pjc42** [comment]
`
                                                                                                                                         
Mon Sep 18 13:18:35 2017                                                                                                                 
source .Rprofile: C:\Users\pjc\Documents/.Rprofile                                                                                       
                                                                                                                                         
Sys.getlocale()                                                                                                                        

[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIM
E=English_United States.1252"                                                                                                            


l10n_info()          
                                                                                                                  
$MBCS                                                                                                                                    
[1] FALSE                                                                                                                                
                                                                                                                                         
$`UTF-8`                                                                                                                                 
[1] FALSE                                                                                                                                
                                                                                                                                         
$`Latin-1`                                                                                                                               
[1] TRUE                                                                                                                                 
                                                                                                                                         
$codepage                                                                                                                                
[1] 1252                                                                                                                                 
                                                                                                                                         
                                                 
`

**Comment by randy3k** [comment]
should be fixed by  bf7fe6c

**Comment by randy3k** [comment]
v0.0.19 is released.
