### ISSUE TITLE
A way to prevent bottom padding of lines when using rice

### ISSUE THREAD

**Issue by sheriferson** [randy3k/rice#17]
It seems like rice does something to add a padding of a few empty lines in the console after a command is run. Here is an example:

![screenshot 2017-09-19 23 32 15](https://user-images.githubusercontent.com/3160968/30629837-ce7ea83c-9d92-11e7-91a7-01e179a298dc.png)

I ran the command `options()`, which has a lot of output that causes the screen to scroll. What I expect from all applications I've used in the terminal is that the output takes up to the last line in the window. But rice adds a few lines at the bottom. I also see this when using rice with Nvim-R.

Is there a way to prevent that from happening? When using Nvim-R, I have the console at the bottom, so this padding hides more of the last command's output than is needed.

Thanks :)

**Comment by randy3k** [comment]
Hm...but some rooms need to be reserved for the auto-completion menu. But we could make the menu multi-column and take lesser rows. Also added an option to stop the menu from popping up automatically, instead a <tab> is required to trigger the menu.

**Comment by randy3k** [comment]
the menu is now multi column and takes lesser rows. 1df147e16a93d051cbf25ba2dba845208065058f

**Comment by randy3k** [comment]
added an option `rice.complete_while_typing` and no space will be reserved if it is `FALSE`.
A `tab` key is required to trigger the menu though.

**Comment by sheriferson** [comment]
Thanks :) This is really great. Pretty neat solution.
