### ISSUE TITLE
line buffering on stdout

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#18]
If you define a function which prints to stdout, rice buffers the output per line. In the following case `foo` is never printed to the screen in rice.
```r
f <- function() {
  cat("foo")
  Sys.sleep(1)
  cat("\rbar")
}
```

If you explicitly print to stderr (which is unbuffered) `foo` does print.
```r
f <- function() {
  cat("foo", file = stderr())
  Sys.sleep(1)
  cat("\rbar", file = stderr())
}
```

If you run these two functions in the standard R console `foo` is printed in both cases.

This was using rice version 0.0.14

**Comment by randy3k** [comment]
I got completely different results on my local mac and a remote machine running ubuntu.
My mac doesn't want to print "foo" to both stdout and stderr. And the ubuntu machine prints "foo" in both cases.
