### ISSUE TITLE
Nvim-R: Usage: rice^@^@rice: error: no such option: --no-save^@

### ISSUE THREAD

**Issue by sheriferson** [randy3k/Rice#2]
Hey,

I understand that there is only partial support for Nvim-R, but I thought I'd report this issue.

After setting `let R_app = 'rice'`, I get this error message when trying to start Nvim-R with an R file open:

`Usage: rice^@^@rice: error: no such option: --no-save^@`

I tried both `pip install rice` and `pip install git+https://github.com/randy3k/rice`.

I couldn't find any mentions of this error message in either `rice`'s or Nvim-R's issues. Any idea what the issue is?

Cheers!

**Comment by randy3k** [comment]
try this instead

```
let g:R_app = 'rice'
let g:R_cmd = 'R'
```

**Comment by randy3k** [comment]
Please note that it now only send the selection / line to rice but not evaluate it. It is because rice and Nvim-R are both "hacking" into R console to send code and rice supports multiline input. There are still some work needed to be done in order to make this happens.

**Comment by randy3k** [comment]
Alright, the master branch `rice` is working with Nvim now.

**Comment by randy3k** [comment]
I think it is now fully operational. Please let me know if it also works for you.

**Comment by randy3k** [comment]
0.0.8 is out.

**Comment by sheriferson** [comment]
It works great! Thanks for making the change so quickly.

**Comment by randy3k** [comment]
BTW, Nvim-R has a settings to turn of the highlight of the terminal, it may be useful.

```
let g:R_app = "rice"
let g:R_cmd = "R"
let g:R_hl_term = 0
```

**Comment by cole-brokamp** [comment]
Hi, I am still experiencing this problem using rice version 0.0.42.dev1

```
  > rice --no-save
Usage: rice

rice: error: no such option: --no-save
```

**Comment by randy3k** [comment]
There is `—no-save` option for rice, that’s why you got the error.

**Comment by cole-brokamp** [comment]
Then why does R say that rice was started with the `--no-save` option?

```
  > rice
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R > commandArgs()
[1] "rice"              "--no-save"         "--no-restore-data" "--quiet"
```

**Comment by randy3k** [comment]
These options are passed to the R engine, but some of them are supported by rice, you can help the options of `rice` by doing `rice -h`.

**Comment by cole-brokamp** [comment]
Thanks for clearing that up.  What I am getting at is that if I attempt to "restart" R within rice using the same startup options as the current session, (e.g. `startup::restart()`) it fails because it tries to pass these underlying options to rice rather than to the R engine.  Is there anyway to prevent this error from happening?

**Comment by randy3k** [comment]
I have just added an environmental variable `RICE_COMMAND_ARGS ` at https://github.com/randy3k/rice/commit/83d32ff764962b93a72921a9aa9a0064be5b9af4
You will need to contact the author of `startup` to utilize this variable when restarting rice.

**Comment by cole-brokamp** [comment]
Thanks, I think this will work, but there seems to be an error where `Sys.getenv('RICE_COMMAND_ARGS')` returns `--no_history` instead of `--no-history`.

When this is fixed, restarting R through rice via the `startup` package will be possible with:

```
startup::restart(args = ifelse(commandArgs()[1] == 'rice', Sys.getenv('RICE_COMMAND_ARGS'), NULL ))

```

**Comment by randy3k** [comment]
ai....you are right, fixed now https://github.com/randy3k/rice/commit/ea2597a7b2814bde6ab5a2499feeef6e5d8b8c23
