### ISSUE TITLE
update `options(width)` with terminal window size

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#20]
The RStudio console, RGui.exe and [R-devel](https://mailman.stat.ethz.ch/pipermail/r-devel/2017-September/074867.html) all have options to adjust `options("width")` when the window is resized. It would be nice if rice did the same.

**Comment by randy3k** [comment]
Done 5f057bd3885e5a4323fdfa3b0b7a92deb7a16d5c.

**Comment by randy3k** [comment]
You could use the option `setWidthOnResize` as in R-devel to update terminal width on resizing.

**Comment by randy3k** [comment]
Added an option `rice.auto_width` to mask the setting `setWidthOnResize`.

**Comment by randy3k** [comment]
FIXME: not working on Windows.

**Comment by randy3k** [comment]
0.0.26 is out.
