### ISSUE TITLE
Maintain and read `.Rhistory` / in-memory history

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#21]
rice seems to maintain it's own history file independant of the R native `.Rhistory`. This is fine, but it should really continue to update R's internal history as well. The current behavior is a problem when trying to use R's debugger (with `browser()`) because you no longer have access to previous commands.

Also in general use of `browser()` seems to break out of the `rice()` shell completely, it would be great to be able to continue to use rice features in that case (I am not sure if it is possible however).

**Comment by randy3k** [comment]
Thanks for the feedback. If I understand correctly, the native R console saves history to a `.Rhistory` in the current directory. I am not sure if I like the idea of having dozens of `.Rhistory` files all over my computer. On the other hand, rice saves history globally to the file `~/.rice_history`, it is also a common practice for other REPLs (e.g., ipython and julia) to store history in one file. Although, some customization would be helpful.

Back to the `browser()`, I am now improving the history functionality of the `Browser` prompt.
What do you mean when you said `browser()` breaks out rice shell? Are there other things not working beside the command history?

**Comment by jimhester** [comment]
Things that don't work

- iterating up the history
- syntax highlighting
- multiline expressions
- completions

The only thing that seems to work is the iterative history search, but even that is not quite right, it should add the command to the `Browse[1]>` prompt, but it inserts the standard prompt.

Using a global history is fine, but it should probably still read local `.Rhistory` files if they already exist, and write the current sessions history to `.Rhistory` if `savehistory()` is called.

Also personally I much prefer per project histories to global histories, I generally want to retrieve the commands I previously ran with the current project, not the commands on unrelated projects.  I wrote a zsh plugin [per-directory-history](https://github.com/jimhester/per-directory-history) to have local histories per directory in zsh for this reason. Being able to easily toggle between a global and local history can be useful however...

**Comment by randy3k** [comment]
Thank you. Supporting the debug prompt should be easy.

Regarding `savehistory` and `loadhistory`, while it is easy to read/write history from/to current session on POSIX system by providing suitable [callbacks](https://github.com/randy3k/rice/blob/3cb08fdfd7a724acf1778cbcb3f5453574aa21ff/rice/session.py#L182-L184), on Windows system, it seems we need some kind of [hacks](https://github.com/rstudio/rstudio/blob/94345017e7d19e73b8a974a2a170ec480ad97de0/src/cpp/r/R/Tools.R#L618). Also `.Rhistory` doesn't support mutliline and doesn't have timestamps, merging the global history and local history also raises some challenges.

Though it is a bit more difficult to implement `savehistory` and `loadhistory`, it should be relatively easy to support a setting like
```
rice.local_history = TRUE
```
to save history in a file local to the current directory.

**Comment by randy3k** [comment]
The debug prompt should be now fully supported 4c8942a578e1dda1a486397abada752f4826ceae.

**Comment by jimhester** [comment]
Maybe it would be sufficient to support reading existing `.Rhistory` with `loadhistory()` so you wouldn't have to worry about multiline or timestamps.

**Comment by randy3k** [comment]
`loadhistory` is still tricky. As `.Rhistory` doesn't have time stamps, shall the local history be put after all the global history or visa verse? It may be easier to support a local version of `.rice_history` and abandon `savehistory` and `loadhistory`.

**Comment by jimhester** [comment]
Sure that makes sense to me

**Comment by randy3k** [comment]
rice now uses a local `.rice_history` if it exists.
e76d875290a6c9e645bd5bd885f2eb35a8d5f58b

**Comment by randy3k** [comment]
Will add an option in rice command line to create such file or suppress the use of any history files.

**Comment by randy3k** [comment]
implemented per-directory history https://github.com/randy3k/rice#history-file
