### ISSUE TITLE
Expose `--no-restore-data` and `--no-save` options

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#23]
As part of #10 rice now exposes some of the options, but not everything. In particular `--no-restore-data` and `--no-save`, which means that rice always restores the workspace in `.RData` exists, and saves it when using `q()`. Also the implementation of `--vanilla` is not quite right as it does not set these options either.

It looks like you can pass them to the R process at https://github.com/randy3k/rice/blob/257d0360b9362c0ca973249038b0b939deeaa9b5/rice/session.py#L83-L85

I was planning on sending a PR to add these, but I am not sure how you would prefer to pass the options down to the RSession class.

**Comment by jimhester** [comment]
`--no-save` is maybe not so important, as you set that explicitly for all rice processes, but not being able to turn off loading of `.RData` images is problematic.

**Comment by randy3k** [comment]
Thanks for the commits, I will simply pass `--no-restore-data` as default. I didn't encounter such issue because I never save an .Rdata object.

**Comment by randy3k** [comment]
`-no-restore-data` is now the default ee871e45b25b30c0b164b8d8878efbef5703f1d5

**Comment by randy3k** [comment]
v0.0.28 is out

**Comment by jacob-long** [comment]
I would love to see you expose these options in a more direct way. I *want* to save `.Rdata` and restore by default, but as far as I can tell I cannot ask `rtichoke` to do this behavior that is (I think) default behavior with R. I can see an argument for having different defaults than R — after all, the value of `rtichoke` is partly tied to being different — but at minimum I'd ask that you consider offering `--save` and `--restore-data` as command line options.

**Comment by randy3k** [comment]
I have just added supports of `--save and --restore-data`. Please checkout current master or wait for the next release.

**Comment by HenrikBengtsson** [comment]
Here's an example where `--no-save` causes rtichoke to fail:
```r
$ rtichoke --version
rtichoke version: 0.1.2
r executable: /usr/lib/R/bin/R
r version: 3.4.4
python executable: /usr/bin/python3
python version: 3.5.2

$ rtichoke 
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> commandArgs()                                                                 
[1] "rtichoke"          "--no-save"         "--no-restore-data"
[4] "--quiet"

## Restart R the same way it was launched:
r$> startup::restart(debug = TRUE)                                                  
0.000s: Restarting R ...
0.074s: - R executable: rtichoke
0.074s: - Command-line arguments: --no-save --no-restore-data
0.075s: - Environment variables: 
0.075s: - quitting current R session
0.075s: Restarting R ... done
Usage: rtichoke

rtichoke: error: no such option: --no-save
```

**Comment by randy3k** [comment]
There is only `—save` but not `—no-save` because no-save is the default

**Comment by HenrikBengtsson** [comment]
Yeah, I understand that, but look at `R --help` (where it exists) and look at what `commandArgs()` claims how rtichoke was launched.  An alternative interpretation is that the `commandArgs()` output is invalid.

I can easily give an informative error message in `startup::restart()` saying that restarting `rtichoke` is not supported, but there might be other R packages/R code out there that relies on `commandArgs()` for launching/re-launching an R session based on the current one. PS. I've validated that `startup::restart()`, which peeks at `commandArgs()`, works on plain R, RStudio Terminal, Rgui (Windows), and ESS.

**Comment by randy3k** [comment]
`commandArgs` doesn't return the arguments for `rtichoke`, it returns the arguments passed to the R engine. The environmental variable `RTICHOKE_COMMAND_ARGS` is what you need to restart `rtichoke`.

**Comment by HenrikBengtsson** [comment]
I'll look into adding that as a workaround for rtichoke to `startup::restart()`.  Note I used `startup::restart()` as an illustration/example to what could be a problem elsewhere, e.g. the R environment (here `commandArgs()[1]`) that `rtichoke` provides might not meet the expectation of existing R code.  Please take this as constructive feedback - not a complaint - I just want to raise this as a potential problem with rtichoke.

**Comment by randy3k** [comment]
Yeah, I totally understand, but I also want to stress that one should not expect that `rtichoke` understands all the arguments of `commandArgs()` because those are the options passed to the internal R engine.

Coming back to the restart issue, the following works
```
startup::restart(args=Sys.getenv("RTICHOKE_COMMAND_ARGS"))
```

**Comment by HenrikBengtsson** [comment]
Why is `commandArgs()[1]` set to `"rtichoke"` in the first place?

**Comment by randy3k** [comment]
Well, it is a convention just it to set an unique name while embedding R. For the case of rtichoke, `rtichoke` is the most obvious name.

**Comment by HenrikBengtsson** [comment]
Just re-read `?commandArgs` and your approach seems to meet it's description, specifically "The first element is the name of the executable by which R was invoked ... or for an embedded R it can be anything the programmer supplied."
