### ISSUE TITLE
HIST_IGNORE_DUPS equivalent setting for history

### ISSUE THREAD

**Issue by jimhester** [randy3k/rice#26]
ZSH has a [`HIST_IGNORE_DUPS` option][1] which will
> not enter command lines into the history list if they are duplicates of the previous event.

It would be nice to have a similar option for the rice history, having duplicate events makes using the incremental search more cumbersome than it otherwise would be. 

Another option would be implementing `HIST_FIND_NO_DUPS`, which simply does not return duplicate entries when searching the history.

Basically if I am using incremental backwards search I don't want to go through the same entry multiple times.

[1]: http://zsh.sourceforge.net/Doc/Release/Options.html

**Comment by randy3k** [comment]
`rice` does not insert the current command into history unless it is not exactly equal to the last entered command. It is easy to implement the `HIST_IGNORE_DUPS` option by extending the match to all commands in the history. I am a bit unsure about `HIST_FIND_NO_DUPS` though. I have to dig into `prompt_toolkit` to give you an answer.

**Comment by jimhester** [comment]
So it sounds like the current behavior is already doing `HIST_IGNORE_DUPS` then. Doing it globally would be equivalent to `HIST_IGNORE_ALL_DUPS`, which be an OK solution. I generally only use history for looking up previous commands, and basically never to replay/record commands in a given session.

**Comment by randy3k** [comment]
Aha, you are right. I do prefer keeping the linearity of the history and am more leaning to the “find no dups” solution.

Note to myself: Regarding the solution, it could be done in overriding the matching condition to filter already shown items. https://github.com/randy3k/rice/blob/28191ef76a4a0424ac4eb66dbf0eff1068a0a75b/rice/deps/prompt_toolkit/buffer.py#L858

**Comment by randy3k** [comment]
It took me a while to understand `prompt_toolkit` code. b7fff9f0cf2993e0f36735882c413e79fb4b0dd0 has introduced a setting `rice.history_search_no_duplicates` which implements the "no duplicates" search. Try it out.
