### ISSUE TITLE
Rice opens 32bit version of R instead of 64bit and fails to load libraries

### ISSUE THREAD

**Issue by janvydra** [randy3k/rice#30]
Hello, I tried to setup rice on Win10 64bit, miniconda 64. 

rice opens R 32:
```
R version 3.4.3 (2017-11-30) -- Kite-Eating Tree
Platform: x86_64-w64-mingw32
```

but R command opens R 64:
```
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
```

but in rice library(dplyr)  [or any other library] show error:

```
> Error: package or namespace load failed for ‘dplyr’ in inDL(x, as.logical(local), as.logical(now), ...):
>  unable to load shared object 'C:/Users/vydra/Documents/R/R-3.4.3/library/stats/libs/x64/stats.dll'

```
this does not happen in plain R terminal, as it opens R64.
Is it possible to force rice to load R 64 version?

Best regards,
Jan

**Comment by randy3k** [comment]
rice uses multiple clues to detect the version of R. 1. It checks the environment variable `R_HOME`, 2 the PATH variable, 3 Windows registry. Could you report the result of `sessionInfo()`?

**Comment by janvydra** [comment]
similar problem on sessionInfo():
```
Error in La_library() : LAPACK routines cannot be loaded
In addition: Warning message:
In La_library() :
  unable to load shared object 'C:/Users/vydra/Documents/R/R-3.4.3/modules/x64/lapack.dll':
  LoadLibrary failure:  Uvedený modul nebyl nalezen.
```
R_HOME is set to R 3.4.3 root directory. 
R is installed for current user only without admin rights. This might be a problem I guess.

Jan

**Comment by randy3k** [comment]
Are you using a special distribution of R?

**Comment by janvydra** [comment]
Just normal R downloaded from CRAN

**Comment by randy3k** [comment]
🤔 let me grab a VM and try it.

**Comment by randy3k** [comment]
I confirm that I have the same issue for R 3.4.3, but it is not because 32bit R was loaded. You should be able to verify it by running `R.Version()`.

**Comment by randy3k** [comment]
It seems that in R 3.4.3, we need to expose the path to R.exe in the PATH variable.

<img width="399" alt="screen shot 2017-12-29 at 1 57 52 am" src="https://user-images.githubusercontent.com/1690993/34431270-b73f16aa-ec3b-11e7-83c4-3e7900bc088d.png">

**Comment by randy3k** [comment]
I have some clues on how to fix it so that R can be detected from the registry. Meanwhile, Windows users will need to make sure that the path to R is included in `PATH`.

**Comment by randy3k** [comment]
It turns out I have failed to fix the detection of R via Windows registry. From now one, users have to specify the PATH to R in the `PATH` variable.
