### ISSUE TITLE
API for custom completions

### ISSUE THREAD

**Issue by klmr** [randy3k/rice#32]
Is there (or are there plans for) an API to add custom completions?

For example, rice correctly completes package names inside a function call to `library` and `require`.  [This is currently hard-coded](https://github.com/randy3k/rice/blob/7d7cc1d65d1f24b5202d70192dcf7b4a33588157/rice/completion.py#L14). It would be helpful for users to be able to add similar completion for other NSE calls. The conventional example is obviously dplyr but I’m more interested in this for an own package, where NSE is used to specify module imports in a very similar way to `library`.

For instance, the user would write

```r
mod::use(klm
```

And the completion could suggest `klmr/sys` (which is an [actual module](https://github.com/klmr/sys)).

In the above example the function is using NSE and the argument is hence unquoted. But of course it would also make sense to be able to provide custom completion for quoted arguments.

**Comment by randy3k** [comment]
try https://github.com/jimhester/completeme

**Comment by klmr** [comment]
Awesome, this looks very promising.

![screen shot 2018-02-09 at 09 36 12](https://user-images.githubusercontent.com/38931/36021108-b3680868-0d7c-11e8-8c00-3405bbbe01d8.png)

I’ll play around with it when I find time!
