### ISSUE TITLE
Permission and lib paths

### ISSUE THREAD

**Issue by adibender** [randy3k/rice#33]
I have some troubles with permissions. 

After installation my already installed packages are not found, because my user library is not in the path
`.libPaths()`. The libraries that are in `.libPaths()` are not writeable and when I try to create add my user library via `.libPaths(new = "/home/username/...")` within `rice`, nothing happens. 

Any suggestions?

**Comment by randy3k** [comment]
You could use the environmental variable `R_LIBS_USER `

https://csg.sph.umich.edu/docs/R/localpackages.html

**Comment by adibender** [comment]
Hm, doesn't appear to work. I verified that it works with normal `R`, but when I open `rice`, the newly defined path in `R_LIBS_USER` doesn't show up in `.libPaths()`. 

BTW, everything runs smoothly on my home computer, but not work computer

**Comment by adibender** [comment]
Yes. I changed `R_LIBS_USER` and started `R` in the console. Calling `.libPaths()` showed expected library specified in `R_LIBS_USER`. Doing the same in `rice`, `.libPaths()` does not show the specified `R_LIBS_USER` library. There appears to be something else to be going on. 
I'll get back to you with more information when I have time, close for now! 

Thanks for the help so far!
