### ISSUE TITLE
Detect when running R via Rice?

### ISSUE THREAD

**Issue by HenrikBengtsson** [randy3k/Rice#4]
Is there a way to detect from within R that it's running via Rice?  Scanning options and env variables, I found env var `_` was set to `/use/local/bin/rice` but not sure if that's reliable, shell specific, or cross platform;
```r
>  env <- Sys.getenv()                                                                                                                                                                                       
>  env[grep("rice", env, ignore.case = TRUE)]                                                                                                                           
_                                                 /usr/local/bin/rice
```

I'm asking because one often wanna use different settings (e.g. R prompt) for different terminals.  If I there's a straightforward way to detect it, I'll add it to the [startup](cran.r-project.org/web/packages/startup) package so R startup files can be included using file / directory names containing `rice=TRUE` and `rice=FALSE`.

PS. Rice looks really nice and promising.  The fact that it also works over SSH is neat.

**Comment by randy3k** [comment]
Good point.

I have added an environmental variable `RICE_VERSION` in 184a720c9889ca00d9913096331ec3313d61ba63

You could install the developmental version of `rice`.

In R, 
```
Sys.getenv("RICE_VERSION")
```

<img width="311" alt="screen shot 2017-09-10 at 1 42 48 pm" src="https://user-images.githubusercontent.com/1690993/30251479-f30bd4d4-962d-11e7-8c74-c6550a07b253.png">

**Comment by HenrikBengtsson** [comment]
Thxs. Developers version of startup is not Rice aware, cf. https://github.com/HenrikBengtsson/startup/commit/9b1442eae3f8e58d2b2379a556e134df7a85d03a
