### ISSUE TITLE
rice doesn't play nicely with reticulate

### ISSUE THREAD

**Issue by goldingn** [randy3k/rice#7]
Sorry to post another one so soon!

rice seems to panic when loading a python module via reticulate:
![screen shot 2017-09-12 at 1 09 19 pm](https://user-images.githubusercontent.com/4450731/30306473-b7a4a51c-97bb-11e7-9dce-f980f6ccc699.png)

no such issues in the default R terminal

**Comment by randy3k** [comment]
I am not surprised. rice is a Python program with embedded R process. And now you are trying to embed again a python process in R. Some work has to be done in reticulate to enable this.

**Comment by Non-Contradiction** [comment]
I develope an R package JuliaCall which embeds julia in R. Similar to the reticulate case, if you use `PyCall.jl` with JuliaCall in rice, some seg fault will happen.

**Comment by randy3k** [comment]
I don't expect JuliaCall will segfault. In fact, I got it running on my machine.

<img width="604" alt="screen shot 2017-09-26 at 12 54 05 pm" src="https://user-images.githubusercontent.com/1690993/30873005-d86a32a4-a2b9-11e7-864c-fd97de22330e.png">

**Comment by Non-Contradiction** [comment]
Yes, it works! My meaning is if use `PyCall.jl` in JuliaCall, like `julia_library("PyCall")`, and segfault will happen. I think it's similar issue to reticulate case?

**Comment by randy3k** [comment]
There should be a workaround for calling `PyCall.jl` via JuliaCall in rice. 
There is some evidence that `PyCall.jl` can be embedded in a python environment, see [pyjulia](https://github.com/JuliaPy/pyjulia)

**Comment by Non-Contradiction** [comment]
I'll check with that, an interesting project.

**Comment by randy3k** [comment]
Ai, you may need to ensure that `PyCall` uses the same python executable as `rice`.

```
(rmbpro)-~$ which python
/Users/Randy/miniconda3/bin/python
```

```
julia> ENV["PYTHON"] = "/Users/Randy/miniconda3/bin/python"
"/Users/Randy/miniconda3/bin/python"

julia> Pkg.build("PyCall")
```

But still, I am getting a segfault.

**Comment by randy3k** [comment]
It turns out that the fix 7380b98456d5e5b7265965f8f2ff12e0d668569e is easy.

```
r$> library(JuliaCall)

r$> julia <- julia_setup()
Julia at location /Applications/Julia-0.6.app/Contents/Resources/julia/bin will be used.
Julia version 0.6.0 found.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.

r$> julia$eval_string("using PyCall")
NULL

r$> julia$eval_string('@pyimport math; math.sin(math.pi)')
[1] 1.224647e-16
```

**Comment by randy3k** [comment]
The situation of `reticulate` has been improved.

```
R version 3.4.1 (2017-06-30) -- Single Candle
Platform: x86_64-apple-darwin16.7.0

r$> library(reticulate)

r$> os <- import("os")
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ImportError: 'rpycall' is not a built-in module

Detailed traceback:
  File "/usr/local/lib/R/3.4/site-library/reticulate/python/rpytools/call.py", line 2, in <module>
    import rpycall
```

**Comment by randy3k** [comment]
I can confirm that `rice` works with python 2.7.

```r
r$> library(reticulate)

r$> os <- import("os")

r$> os$getcwd()
[1] "/Users/Randy/Dropbox/R/rice"
```

However, one needs to confirm that `reticulate` is using the same `python` process which `rice` uses.

```r
r$> reticulate:::py_config()
python:         /Users/Randy/miniconda3/envs/py27/bin/python
libpython:      /Users/Randy/miniconda3/envs/py27/lib/libpython2.7.dylib
pythonhome:     /Users/Randy/miniconda3/envs/py27:/Users/Randy/miniconda3/envs/py27
version:        2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
numpy:          /Users/Randy/miniconda3/envs/py27/lib/python2.7/site-packages/numpy
numpy_version:  1.13.1
os:             /Users/Randy/miniconda3/envs/py27/lib/python2.7/os.py

python versions found:
 /Users/Randy/miniconda3/envs/py27/bin/python
 /usr/bin/python
 /Users/Randy/miniconda3/bin/python
```

**Comment by randy3k** [comment]
For python 3, it depends on https://github.com/rstudio/reticulate/pull/104

So I consider it is fixed.

**Comment by randy3k** [comment]
@Non-Contradiction I got no segfault from `reticulate` to `pyjulia` to `julia`. So I assume that the segfault is caused by JuliaCall.

```
R version 3.4.1 (2017-06-30) -- Single Candle
Platform: x86_64-apple-darwin16.7.0

r$> library(reticulate)

r$> julia <- import("julia")

r$> j <- julia$Julia()

r$> j$eval("versioninfo()")
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by Non-Contradiction** [comment]
I'm not sure. 

The segfault appears when R session is end, which triggers Julia quitting, which triggers the decreasing of reference counting numbers as in L95-99 in <https://github.com/JuliaPy/PyCall.jl/blob/master/src/PyCall.jl>. 

I try to use pyjulia and PyCall to reproduce this, but not successful. For example, 

    Python 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import julia
    >>> j = julia.Julia()
    >>> j.eval("exit()")
    lichangchengdeMacBook:pyjulia lichangcheng$

It's kind of weird to me, because when I want to end the embedded julia, I end python as well as julia. Maybe this is because pyjulia use fake julia?

**Comment by randy3k** [comment]
It seems there is no issue when `julia$eval_string("exit()")` is called explicatly.

**Comment by randy3k** [comment]
@goldingn check https://github.com/randy3k/rice#reticulate-is-not-working

**Comment by goldingn** [comment]
works perfectly, thanks!
