### ISSUE TITLE
Customized R prompt not working in Rice

### ISSUE THREAD

**Issue by JackieMium** [randy3k/Rice#9]
Nice little tool !
I have a line in my `~/.Rprofile`:
```R
options(prompt="\033[0;36mR>>\033[0m"
```
to customize the R prompt style and color. It worked in R console and in RStudio daily build(yes, stable build does not support this yet ), but Rice won't parse it.

Another thing is that when I type in Rice, the code completion pops up and I use UP-DOWN arrow key to navigate through all cadidate, but when I hit ENTER, the line will be submitted and ran, which is not good logci. In `zsh` or `RStudio`, where code completion is implemented, hitting ENTER will usually just input the code completion candidate you choose, not run it immediatly. This is annoying because when I am typing and using code completion, it usually means the line is not done yet. For example, when I input `library(MA`,  `MASS` pops up and I navigate to it and hit ENTER, the line will run. However, a right braket is absent and the code definitely won't run properly.

**Comment by randy3k** [comment]
You are right that rice doesn't honor that option. Theoretically, `rice` should be able to support it.

For your second issue, which version of `rice` are you using? The latest version should not submit the code when enter is hit.

**Comment by JackieMium** [comment]
@randy3k I am using `rice 0.0.12` under ` Debian sid x86_64`,  R version `3.4.1 (2017-06-30) -- "Single Candle"`

**Comment by randy3k** [comment]
The completion issue is fixed at the master branch, I thought I have fixed it but there was a bug.

**Comment by JackieMium** [comment]
OK, waiting for a perfect solution.

**Comment by randy3k** [comment]
I am now working on the prompt.

**Comment by randy3k** [comment]
All fixed, `pip install git+https://github.com/randy3k/rice` will install the latest commit.

**Comment by randy3k** [comment]
Oops, it was a false +ve

**Comment by JackieMium** [comment]
I've got the dev version installed now. When ENTER is hitted, a new line is inserted(or, should I say the the input cursor goes to the next line?), is it supposed to be like this?

**Comment by randy3k** [comment]
It was the bug that I mentioned earlier, it should be fixed by 657e856.

The prompt issue was also addressed at 2064555263fd99be2b14c205ae60d857c48a16ea

![sep-14-2017 01-05-54](https://user-images.githubusercontent.com/1690993/30412902-efe8d708-98e8-11e7-99e7-ab154ef6fc6b.gif)

**Comment by randy3k** [comment]
Did you force it to install?

```
pip install -I git+https://github.com/randy3k/rice
```

**Comment by JackieMium** [comment]
Problem solved.
I guess the ` force to install` option did the trick. Didn't know anything about that earlier, sorry.

**Comment by randy3k** [comment]
Glad that it also works for you.

v0.0.13 is released.
